name: Test at PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - '.github/**'

env:
  LANG: "en_US.UTF-8"
  ImageOS: ubuntu18
  GRADLE_USER_HOME: ./gradle-cache

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout in Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set en_US.UTF-8
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Install Android SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip
          rm commandlinetools-linux-6858069_latest.zip
          mkdir vendor/cmdline-tools
          mv cmdline-tools vendor/cmdline-tools/
          mv vendor/cmdline-tools/cmdline-tools vendor/cmdline-tools/tools
          export PATH=$(pwd)/vendor/cmdline-tools/:$(pwd)/vendor/cmdline-tools/tools/bin:$PATH
          yes | sdkmanager "platforms;android-30"
          yes | sdkmanager "build-tools;30.0.3"
          yes | sdkmanager --install "ndk;20.0.5594570"

      - name: Run Android tests
        run: ./gradlew connectedAndroidTest

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/androidTests/connected/